# Build on pre-configured base image
FROM navidrome_navidrome_v0.57.0_v0.58.0/base:latest

# Install Ginkgo CLI for spec-level test reporting
RUN cd /testbed && go install github.com/onsi/ginkgo/v2/ginkgo@v2.23.4

# Remove the original /testbed from base image and copy local testbed
RUN rm -rf /testbed
COPY . /testbed/

# Set default git state to START
RUN cd /testbed && git checkout milestone-milestone_007-start
